In [5]:
import numpy as np

a = np.array([1,2,3,4])

a



array([1, 2, 3, 4])

In [6]:
a.ndim


1

In [7]:
a.shape

(4,)

In [8]:
len(a)

4

In [9]:
b=np.array([[0,1],[2,3],[4,5],[6,7]])
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(4, 2)

In [13]:
len(b)

4

In [19]:
a=np.array([[[0,1],[2,3]],[[2,3],[2,5]]])
a

array([[[0, 1],
        [2, 3]],

       [[2, 3],
        [2, 5]]])

In [20]:
a.ndim

3

In [21]:
a.shape

(2, 2, 2)

In [22]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
c=np.arange(2,5)
c

array([2, 3, 4])

In [25]:
d=np.arange(0,16,3)
d

array([ 0,  3,  6,  9, 12, 15])

In [28]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
a=np.ones([2,2])
2*a

array([[2., 2.],
       [2., 2.]])

In [35]:
a=np.eye(5)
3*a

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [37]:
a=np.eye(4,8)
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [38]:
np.diag(a)

array([1., 1., 1., 1.])

In [42]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
np.diag(a)

array([1, 2, 3, 4])

In [44]:
a=np.arange(10)
print(a[7])

7


In [45]:
a = np.diag([1,2,3,4])
print(a.shape)

(4, 4)


In [46]:
print(a[3][1])

0


In [47]:
a[3][1] = 5

print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 5 0 4]]


In [3]:
import numpy as np

p=np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
p[5:8] = 10
p

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [5]:
q=np.arange(4)
q

array([0, 1, 2, 3])

In [15]:
p[8:] = q[::-2]
p

array([ 0,  1,  2,  3,  4, 10,  3,  2,  3,  1])

In [16]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = a[1:6:1]
b

array([1, 2, 3, 4, 5])

In [18]:
b[0] = 0
b

array([0, 2, 3, 4, 5])

In [19]:
np.shares_memory(a,b)

True

In [20]:
a

array([0, 0, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
c = a[1:6:1].copy()
c

array([0, 2, 3, 4, 5])

In [22]:
np.shares_memory(a,c)

False

In [23]:
p = np.random.randint(2,10,20)
p

array([9, 7, 9, 7, 3, 3, 2, 7, 5, 3, 7, 2, 6, 4, 8, 2, 2, 5, 9, 4])

In [25]:
mask = (p%2==0)
 
subset_p = p[mask]
subset_p

array([2, 2, 6, 4, 8, 2, 2, 4])

In [26]:
len(subset_p)

8

In [27]:
len(p)

20

In [28]:
a = np.arange(5)
a+1

array([1, 2, 3, 4, 5])

In [29]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [33]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [34]:
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [35]:
a*b

array([0., 1., 2., 3., 4.])

In [37]:
c=np.diag([1,2,3])
print(c*c)
print("***********************")
print(c.dot(c))

[[1 0 0]
 [0 4 0]
 [0 0 9]]
***********************
[[1 0 0]
 [0 4 0]
 [0 0 9]]


In [38]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])

print(a==b)

[False False False False False]


In [39]:
print(b>a)

[ True  True  True  True  True]


In [41]:
c=np.array([1,2,3,4,5])

print(np.array_equal(a,c))
print(np.array_equal(a,b))

True
False


In [43]:
x = np.arange(5)
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
x = [1,2,3,4,5]
np.sum(x)

15

In [47]:
y = np.array([[1,2],[2,3]])
y

array([[1, 2],
       [2, 3]])

In [48]:
y.sum(axis=0)

array([3, 5])

In [49]:
y.sum(axis=1)

array([3, 5])

In [50]:
x= np.array([1,3,5,2,5,7])
x.min()

1

In [51]:
x.max()

7

In [52]:
x.argmin()

0

In [53]:
x.argmax()

5

In [55]:
np.all([1,0,0,1])

False

In [57]:
np.any([1,1,1,1,0])

True

In [60]:
a = np.zeros((20,20))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [61]:
np.any(a!=0)

False

In [62]:
a[13][0] = 7
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [63]:
np.all(a!=0)

False

In [64]:
np.any(a=7)

True

In [65]:
x = np.array([1,2,3,4,5])
y = np.array([[1,2],[2,2]])

In [66]:
print("Mean of x is:",x.mean())

Mean of x is: 3.0


In [68]:
np.median(x)

3.0

In [69]:
np.sum(x)

15

In [70]:
np.mean(y,axis=0)

array([1.5, 2. ])

In [71]:
np.mean(y,axis = 1)

array([1.5, 2. ])

In [72]:
np.sum(y)

7

In [73]:
np.sum(y,axis = 1)

array([3, 4])

In [77]:
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [78]:
year,hare,lynxes,carrot = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [79]:
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [80]:
np.mean(population,axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [81]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [82]:
np.argmax(population,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [89]:
a = np.tile(np.arange(0,50,10),(3,1))
print(a)
print("******************************")
a=a.T
print(a)

[[ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]]
******************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [40 40 40]]


In [102]:
b=np.array([0,1,2,3,4])
print(b)
print(b.shape)
print("*************************************")
b = b[:,np.newaxis]

print(b)
print(b.shape)


[0 1 2 3 4]
(5,)
*************************************
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [103]:
a+b

array([[ 0,  0,  0],
       [11, 11, 11],
       [22, 22, 22],
       [33, 33, 33],
       [44, 44, 44]])

In [105]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [106]:
print(b.ravel())

[1 2 3 4 5 6]


In [108]:
print(b.T.ravel())

[1 4 2 5 3 6]


In [109]:
print(b)

[[1 2 3]
 [4 5 6]]


In [110]:
c=b.ravel()
print(c)

[1 2 3 4 5 6]


In [111]:
c=c.reshape((2,3))
print(c)

[[1 2 3]
 [4 5 6]]


In [112]:
c=c.reshape((3,2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [114]:
x=np.arange(4*3*2).reshape((4,3,2))
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [115]:
a  = x[1,0,1]
print(a)

7


In [121]:
p = np.arange(5)
print(p)
p.resize((8,))
print(p)

[0 1 2 3 4]
[0 1 2 3 4 0 0 0]


In [126]:
a=np.array([[5,1,9],[6,3,7]])
print(a)
a.sort(axis=1)
print(a)
a.sort(axis=0)
print(a)

[[5 1 9]
 [6 3 7]]
[[1 5 9]
 [3 6 7]]
[[1 5 7]
 [3 6 9]]


In [127]:
a=np.array([3,5,1,9,0])
print(a)

[3 5 1 9 0]


In [130]:
j=np.argsort(a)
#print(j)

In [131]:
print(a[j])

[0 1 3 5 9]


In [134]:
print(a[-j])

[5 9 3 0 1]
